// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Describes the Build step of the function that builds a container from the
/// given source.
public struct BuildConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The Cloud Build name of the latest successful deployment of
  /// the function.
  public var build: Swift.String

  /// The runtime in which to run the function. Required when deploying a new
  /// function, optional when updating an existing function. For a complete
  /// list of possible choices, see the
  /// [`gcloud` command
  /// reference](https://cloud.google.com/sdk/gcloud/reference/functions/deploy#--runtime).
  public var runtime: Swift.String

  /// The name of the function (as defined in source code) that will be
  /// executed. Defaults to the resource name suffix, if not specified. For
  /// backward compatibility, if function with given name is not found, then the
  /// system will try to use function named "function".
  /// For Node.js this is name of a function exported by the module specified
  /// in `source_location`.
  public var entryPoint: Swift.String

  /// The location of the function source code.
  public var source: Source?

  /// Output only. A permanent fixed identifier for source.
  public var sourceProvenance: SourceProvenance?

  /// Name of the Cloud Build Custom Worker Pool that should be used to build the
  /// function. The format of this field is
  /// `projects/{project}/locations/{region}/workerPools/{workerPool}` where
  /// {project} and {region} are the project id and region respectively where the
  /// worker pool is defined and {workerPool} is the short name of the worker
  /// pool.
  ///
  /// If the project id is not the same as the function, then the Cloud
  /// Functions Service Agent
  /// (service-<project_number>@gcf-admin-robot.iam.gserviceaccount.com) must be
  /// granted the role Cloud Build Custom Workers Builder
  /// (roles/cloudbuild.customworkers.builder) in the project.
  public var workerPool: Swift.String

  /// User-provided build-time environment variables for the function
  public var environmentVariables: [Swift.String: Swift.String]

  /// Docker Registry to use for this deployment. This configuration is only
  /// applicable to 1st Gen functions, 2nd Gen functions can only use Artifact
  /// Registry.
  /// Deprecated: As of March 2025, `CONTAINER_REGISTRY` option is no longer
  /// available in response to Container Registry's deprecation:
  /// https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr
  /// Please use Artifact Registry instead, which is the default choice.
  ///
  /// If unspecified, it defaults to `ARTIFACT_REGISTRY`.
  /// If `docker_repository` field is specified, this field should either be left
  /// unspecified or set to `ARTIFACT_REGISTRY`.
  public var dockerRegistry: BuildConfig.DockerRegistry

  /// Repository in Artifact Registry to which the function docker image will be
  /// pushed after it is built by Cloud Build. If specified by user, it is
  /// created and managed by user with a customer managed encryption key.
  /// Otherwise, GCF will create and use a repository named 'gcf-artifacts'
  /// for every deployed region.
  ///
  /// It must match the pattern
  /// `projects/{project}/locations/{location}/repositories/{repository}`.
  /// Repository format must be 'DOCKER'.
  public var dockerRepository: Swift.String

  /// Service account to be used for building the container. The format of this
  /// field is `projects/{projectId}/serviceAccounts/{serviceAccountEmail}`.
  public var serviceAccount: Swift.String

  /// This controls when security patches are applied to the runtime environment.
  public var runtimeUpdatePolicy: OneOf_RuntimeUpdatePolicy?

  /// Initialize a new instance of `BuildConfig`.
  public init(
    build: Swift.String = Swift.String(),
    runtime: Swift.String = Swift.String(),
    entryPoint: Swift.String = Swift.String(),
    source: Source? = nil,
    sourceProvenance: SourceProvenance? = nil,
    workerPool: Swift.String = Swift.String(),
    environmentVariables: [Swift.String: Swift.String] = [:],
    dockerRegistry: BuildConfig.DockerRegistry = BuildConfig.DockerRegistry(),
    dockerRepository: Swift.String = Swift.String(),
    serviceAccount: Swift.String = Swift.String(),
    runtimeUpdatePolicy: OneOf_RuntimeUpdatePolicy? = nil,
  ) {
    self.build = build
    self.runtime = runtime
    self.entryPoint = entryPoint
    self.source = source
    self.sourceProvenance = sourceProvenance
    self.workerPool = workerPool
    self.environmentVariables = environmentVariables
    self.dockerRegistry = dockerRegistry
    self.dockerRepository = dockerRepository
    self.serviceAccount = serviceAccount
    self.runtimeUpdatePolicy = runtimeUpdatePolicy
  }

  private enum CodingKeys: String, CodingKey {
    case automaticUpdatePolicy = "automaticUpdatePolicy"
    case onDeployUpdatePolicy = "onDeployUpdatePolicy"
    case build = "build"
    case runtime = "runtime"
    case entryPoint = "entryPoint"
    case source = "source"
    case sourceProvenance = "sourceProvenance"
    case workerPool = "workerPool"
    case environmentVariables = "environmentVariables"
    case dockerRegistry = "dockerRegistry"
    case dockerRepository = "dockerRepository"
    case serviceAccount = "serviceAccount"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.build = try container.decode(Swift.String.self, forKey: .build)
    self.runtime = try container.decode(Swift.String.self, forKey: .runtime)
    self.entryPoint = try container.decode(Swift.String.self, forKey: .entryPoint)
    self.source = try container.decodeIfPresent(Source.self, forKey: .source)
    self.sourceProvenance = try container.decodeIfPresent(
      SourceProvenance.self, forKey: .sourceProvenance)
    self.workerPool = try container.decode(Swift.String.self, forKey: .workerPool)
    self.environmentVariables = try container.decode(
      [Swift.String: Swift.String].self, forKey: .environmentVariables)
    self.dockerRegistry = try container.decode(
      BuildConfig.DockerRegistry.self, forKey: .dockerRegistry)
    self.dockerRepository = try container.decode(Swift.String.self, forKey: .dockerRepository)
    self.serviceAccount = try container.decode(Swift.String.self, forKey: .serviceAccount)

    var runtimeUpdatePolicy: OneOf_RuntimeUpdatePolicy? = nil
    let runtimeUpdatePolicyCheckAndSet = {
      if runtimeUpdatePolicy != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'runtimeUpdatePolicy'"))
      }
      runtimeUpdatePolicy = $0
    }
    if let automaticUpdatePolicy = try container.decodeIfPresent(
      AutomaticUpdatePolicy?.self, forKey: .automaticUpdatePolicy)
    {
      try runtimeUpdatePolicyCheckAndSet(.automaticUpdatePolicy(automaticUpdatePolicy))
    }
    if let onDeployUpdatePolicy = try container.decodeIfPresent(
      OnDeployUpdatePolicy?.self, forKey: .onDeployUpdatePolicy)
    {
      try runtimeUpdatePolicyCheckAndSet(.onDeployUpdatePolicy(onDeployUpdatePolicy))
    }
    self.runtimeUpdatePolicy = runtimeUpdatePolicy
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.build, forKey: .build)
    try container.encode(self.runtime, forKey: .runtime)
    try container.encode(self.entryPoint, forKey: .entryPoint)
    try container.encode(self.source, forKey: .source)
    try container.encode(self.sourceProvenance, forKey: .sourceProvenance)
    try container.encode(self.workerPool, forKey: .workerPool)
    try container.encode(self.environmentVariables, forKey: .environmentVariables)
    try container.encode(self.dockerRegistry, forKey: .dockerRegistry)
    try container.encode(self.dockerRepository, forKey: .dockerRepository)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)

    if let choice = self.runtimeUpdatePolicy {
      switch choice {
      case .automaticUpdatePolicy(let value):
        try container.encode(value, forKey: .automaticUpdatePolicy)
      case .onDeployUpdatePolicy(let value):
        try container.encode(value, forKey: .onDeployUpdatePolicy)
      }
    }
  }

  /// Docker Registry to use for storing function Docker images.
  public enum DockerRegistry: Codable, Equatable, Sendable {
    case unspecified
    case containerRegistry
    case artifactRegistry
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .containerRegistry: return 1
      case .artifactRegistry: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "DOCKER_REGISTRY_UNSPECIFIED"
      case .containerRegistry: return "CONTAINER_REGISTRY"
      case .artifactRegistry: return "ARTIFACT_REGISTRY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "DOCKER_REGISTRY_UNSPECIFIED": self = .unspecified
      case "CONTAINER_REGISTRY": self = .containerRegistry
      case "ARTIFACT_REGISTRY": self = .artifactRegistry
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .containerRegistry
      case 2: self = .artifactRegistry
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .containerRegistry: return try container.encode(1)
      case .artifactRegistry: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// This controls when security patches are applied to the runtime environment.
  public enum OneOf_RuntimeUpdatePolicy: Codable, Equatable, Sendable {
    indirect case automaticUpdatePolicy(AutomaticUpdatePolicy?)
    indirect case onDeployUpdatePolicy(OnDeployUpdatePolicy?)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.functions.v2.BuildConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
