// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Describes the Build step of the function that builds a container from the
/// given source.
public struct BuildConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The Cloud Build name of the latest successful deployment of
  /// the function.
  public var build: Swift.String = Swift.String()

  /// The runtime in which to run the function. Required when deploying a new
  /// function, optional when updating an existing function. For a complete
  /// list of possible choices, see the
  /// [`gcloud` command
  /// reference](https://cloud.google.com/sdk/gcloud/reference/functions/deploy#--runtime).
  public var runtime: Swift.String = Swift.String()

  /// The name of the function (as defined in source code) that will be
  /// executed. Defaults to the resource name suffix, if not specified. For
  /// backward compatibility, if function with given name is not found, then the
  /// system will try to use function named "function".
  /// For Node.js this is name of a function exported by the module specified
  /// in `source_location`.
  public var entryPoint: Swift.String = Swift.String()

  /// The location of the function source code.
  public var source: Source? = nil

  /// Output only. A permanent fixed identifier for source.
  public var sourceProvenance: SourceProvenance? = nil

  /// Name of the Cloud Build Custom Worker Pool that should be used to build the
  /// function. The format of this field is
  /// `projects/{project}/locations/{region}/workerPools/{workerPool}` where
  /// {project} and {region} are the project id and region respectively where the
  /// worker pool is defined and {workerPool} is the short name of the worker
  /// pool.
  ///
  /// If the project id is not the same as the function, then the Cloud
  /// Functions Service Agent
  /// (service-<project_number>@gcf-admin-robot.iam.gserviceaccount.com) must be
  /// granted the role Cloud Build Custom Workers Builder
  /// (roles/cloudbuild.customworkers.builder) in the project.
  public var workerPool: Swift.String = Swift.String()

  /// User-provided build-time environment variables for the function
  public var environmentVariables: [Swift.String: Swift.String] = [:]

  /// Docker Registry to use for this deployment. This configuration is only
  /// applicable to 1st Gen functions, 2nd Gen functions can only use Artifact
  /// Registry.
  /// Deprecated: As of March 2025, `CONTAINER_REGISTRY` option is no longer
  /// available in response to Container Registry's deprecation:
  /// https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr
  /// Please use Artifact Registry instead, which is the default choice.
  ///
  /// If unspecified, it defaults to `ARTIFACT_REGISTRY`.
  /// If `docker_repository` field is specified, this field should either be left
  /// unspecified or set to `ARTIFACT_REGISTRY`.
  @available(*, deprecated)
  public var dockerRegistry: BuildConfig.DockerRegistry = BuildConfig.DockerRegistry()

  /// Repository in Artifact Registry to which the function docker image will be
  /// pushed after it is built by Cloud Build. If specified by user, it is
  /// created and managed by user with a customer managed encryption key.
  /// Otherwise, GCF will create and use a repository named 'gcf-artifacts'
  /// for every deployed region.
  ///
  /// It must match the pattern
  /// `projects/{project}/locations/{location}/repositories/{repository}`.
  /// Repository format must be 'DOCKER'.
  public var dockerRepository: Swift.String = Swift.String()

  /// Service account to be used for building the container. The format of this
  /// field is `projects/{projectId}/serviceAccounts/{serviceAccountEmail}`.
  public var serviceAccount: Swift.String = Swift.String()

  /// This controls when security patches are applied to the runtime environment.
  public var runtimeUpdatePolicy: OneOf_RuntimeUpdatePolicy? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BuildConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BuildConfig().with { $0.automaticUpdatePolicy = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let automaticUpdatePolicy = CodingKeys(stringValue: "automaticUpdatePolicy")
    static let onDeployUpdatePolicy = CodingKeys(stringValue: "onDeployUpdatePolicy")
    static let build = CodingKeys(stringValue: "build")
    static let runtime = CodingKeys(stringValue: "runtime")
    static let entryPoint = CodingKeys(stringValue: "entryPoint")
    static let source = CodingKeys(stringValue: "source")
    static let sourceProvenance = CodingKeys(stringValue: "sourceProvenance")
    static let workerPool = CodingKeys(stringValue: "workerPool")
    static let environmentVariables = CodingKeys(stringValue: "environmentVariables")
    static let dockerRegistry = CodingKeys(stringValue: "dockerRegistry")
    static let dockerRepository = CodingKeys(stringValue: "dockerRepository")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")

    static let _knownKeys: Set<Swift.String> = [
      "automaticUpdatePolicy",
      "onDeployUpdatePolicy",
      "build",
      "runtime",
      "entryPoint",
      "source",
      "sourceProvenance",
      "workerPool",
      "environmentVariables",
      "dockerRegistry",
      "dockerRepository",
      "serviceAccount",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .build) {
      self.build = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .runtime) {
      self.runtime = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .entryPoint) {
      self.entryPoint = value
    }
    self.source = try container.decodeIfPresent(Source.self, forKey: .source)
    self.sourceProvenance = try container.decodeIfPresent(
      SourceProvenance.self, forKey: .sourceProvenance)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .workerPool) {
      self.workerPool = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .environmentVariables)
    {
      self.environmentVariables = value
    }
    if let value = try container.decodeIfPresent(
      BuildConfig.DockerRegistry.self, forKey: .dockerRegistry)
    {
      self.dockerRegistry = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dockerRepository) {
      self.dockerRepository = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }

    var runtimeUpdatePolicy: OneOf_RuntimeUpdatePolicy? = nil
    let runtimeUpdatePolicyCheckAndSet = {
      if runtimeUpdatePolicy != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'runtimeUpdatePolicy'"))
      }
      runtimeUpdatePolicy = $0
    }
    if let automaticUpdatePolicy = try container.decodeIfPresent(
      AutomaticUpdatePolicy?.self, forKey: .automaticUpdatePolicy)
    {
      try runtimeUpdatePolicyCheckAndSet(.automaticUpdatePolicy(automaticUpdatePolicy))
    }
    if let onDeployUpdatePolicy = try container.decodeIfPresent(
      OnDeployUpdatePolicy?.self, forKey: .onDeployUpdatePolicy)
    {
      try runtimeUpdatePolicyCheckAndSet(.onDeployUpdatePolicy(onDeployUpdatePolicy))
    }
    self.runtimeUpdatePolicy = runtimeUpdatePolicy
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.build, forKey: .build)
    try container.encode(self.runtime, forKey: .runtime)
    try container.encode(self.entryPoint, forKey: .entryPoint)
    try container.encodeIfPresent(self.source, forKey: .source)
    try container.encodeIfPresent(self.sourceProvenance, forKey: .sourceProvenance)
    try container.encode(self.workerPool, forKey: .workerPool)
    try container.encode(self.environmentVariables, forKey: .environmentVariables)
    try container.encode(self.dockerRegistry, forKey: .dockerRegistry)
    try container.encode(self.dockerRepository, forKey: .dockerRepository)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)

    if let choice = self.runtimeUpdatePolicy {
      switch choice {
      case .automaticUpdatePolicy(let value):
        try container.encode(value, forKey: .automaticUpdatePolicy)
      case .onDeployUpdatePolicy(let value):
        try container.encode(value, forKey: .onDeployUpdatePolicy)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Docker Registry to use for storing function Docker images.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum DockerRegistry: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Docker images will be stored in multi-regional Container Registry
    /// repositories named `gcf`.
    case containerRegistry
    /// Docker images will be stored in regional Artifact Registry repositories.
    /// By default, GCF will create and use repositories named `gcf-artifacts`
    /// in every region in which a function is deployed. But the repository to
    /// use can also be specified by the user using the `docker_repository`
    /// field.
    case artifactRegistry
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .containerRegistry: return 1
      case .artifactRegistry: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DOCKER_REGISTRY_UNSPECIFIED"
      case .containerRegistry: return "CONTAINER_REGISTRY"
      case .artifactRegistry: return "ARTIFACT_REGISTRY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DockerRegistry/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DOCKER_REGISTRY_UNSPECIFIED": self = .unspecified
      case "CONTAINER_REGISTRY": self = .containerRegistry
      case "ARTIFACT_REGISTRY": self = .artifactRegistry
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DockerRegistry/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .containerRegistry
      case 2: self = .artifactRegistry
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("DOCKER_REGISTRY_UNSPECIFIED")
      case .containerRegistry: return try container.encode("CONTAINER_REGISTRY")
      case .artifactRegistry: return try container.encode("ARTIFACT_REGISTRY")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// This controls when security patches are applied to the runtime environment.
  public enum OneOf_RuntimeUpdatePolicy: Codable, Equatable, Sendable {
    indirect case automaticUpdatePolicy(AutomaticUpdatePolicy?)
    indirect case onDeployUpdatePolicy(OnDeployUpdatePolicy?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.functions.v2.BuildConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
