// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for the `CreateFunction` method.
public struct CreateFunctionRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The project and location in which the function should be created,
  /// specified in the format `projects/*/locations/*`
  public var parent: Swift.String

  /// Required. Function to be created.
  public var function: Function?

  /// The ID to use for the function, which will become the final component of
  /// the function's resource name.
  ///
  /// This value should be 4-63 characters, and valid characters
  /// are /[a-z][0-9]-/.
  public var functionId: Swift.String

  /// Initialize a new instance of `CreateFunctionRequest`.
  public init(
    parent: Swift.String = Swift.String(),
    function: Function? = nil,
    functionId: Swift.String = Swift.String(),
  ) {
    self.parent = parent
    self.function = function
    self.functionId = functionId
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.functions.v2.CreateFunctionRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
