// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Describes a Cloud Function that contains user computation executed in
/// response to an event. It encapsulates function and trigger configurations.
public struct Function: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A user-defined name of the function. Function names must be unique
  /// globally and match pattern `projects/*/locations/*/functions/*`
  public var name: Swift.String = Swift.String()

  /// User-provided description of a function.
  public var description: Swift.String = Swift.String()

  /// Describes the Build step of the function that builds a container from the
  /// given source.
  public var buildConfig: BuildConfig? = nil

  /// Describes the Service being deployed. Currently deploys services to Cloud
  /// Run (fully managed).
  public var serviceConfig: ServiceConfig? = nil

  /// An Eventarc trigger managed by Google Cloud Functions that fires events in
  /// response to a condition in another service.
  public var eventTrigger: EventTrigger? = nil

  /// Output only. State of the function.
  public var state: Function.State = Function.State()

  /// Output only. The last update timestamp of a Cloud Function.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Labels associated with this Cloud Function.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. State Messages for this Cloud Function.
  public var stateMessages: [StateMessage] = []

  /// Describe whether the function is 1st Gen or 2nd Gen.
  public var environment: Environment = Environment()

  /// Output only. The deployed url for the function.
  public var url: Swift.String = Swift.String()

  /// Resource name of a KMS crypto key (managed by the user) used to
  /// encrypt/decrypt function resources.
  ///
  /// It must match the pattern
  /// `projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}`.
  public var kmsKeyName: Swift.String = Swift.String()

  /// Output only. Reserved for future use.
  public var satisfiesPzs: Swift.Bool = Swift.Bool()

  /// Output only. The create timestamp of a Cloud Function. This is only
  /// applicable to 2nd Gen functions.
  public var createTime: GoogleWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Function`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Function().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let buildConfig = CodingKeys(stringValue: "buildConfig")
    static let serviceConfig = CodingKeys(stringValue: "serviceConfig")
    static let eventTrigger = CodingKeys(stringValue: "eventTrigger")
    static let state = CodingKeys(stringValue: "state")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let stateMessages = CodingKeys(stringValue: "stateMessages")
    static let environment = CodingKeys(stringValue: "environment")
    static let url = CodingKeys(stringValue: "url")
    static let kmsKeyName = CodingKeys(stringValue: "kmsKeyName")
    static let satisfiesPzs = CodingKeys(stringValue: "satisfiesPzs")
    static let createTime = CodingKeys(stringValue: "createTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "description",
      "buildConfig",
      "serviceConfig",
      "eventTrigger",
      "state",
      "updateTime",
      "labels",
      "stateMessages",
      "environment",
      "url",
      "kmsKeyName",
      "satisfiesPzs",
      "createTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.buildConfig = try container.decodeIfPresent(BuildConfig.self, forKey: .buildConfig)
    self.serviceConfig = try container.decodeIfPresent(ServiceConfig.self, forKey: .serviceConfig)
    self.eventTrigger = try container.decodeIfPresent(EventTrigger.self, forKey: .eventTrigger)
    if let value = try container.decodeIfPresent(Function.State.self, forKey: .state) {
      self.state = value
    }
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent([StateMessage].self, forKey: .stateMessages) {
      self.stateMessages = value
    }
    if let value = try container.decodeIfPresent(Environment.self, forKey: .environment) {
      self.environment = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .url) {
      self.url = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKeyName) {
      self.kmsKeyName = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzs) {
      self.satisfiesPzs = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.buildConfig, forKey: .buildConfig)
    try container.encodeIfPresent(self.serviceConfig, forKey: .serviceConfig)
    try container.encodeIfPresent(self.eventTrigger, forKey: .eventTrigger)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.stateMessages, forKey: .stateMessages)
    try container.encode(self.environment, forKey: .environment)
    try container.encode(self.url, forKey: .url)
    try container.encode(self.kmsKeyName, forKey: .kmsKeyName)
    try container.encode(self.satisfiesPzs, forKey: .satisfiesPzs)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Describes the current state of the function.
  public enum State: Codable, Equatable, Sendable {
    /// Not specified. Invalid state.
    case unspecified
    /// Function has been successfully deployed and is serving.
    case active
    /// Function deployment failed and the function is not serving.
    case failed
    /// Function is being created or updated.
    case deploying
    /// Function is being deleted.
    case deleting
    /// Function deployment failed and the function serving state is undefined.
    /// The function should be updated or deleted to move it out of this state.
    case unknown
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .failed: return 2
      case .deploying: return 3
      case .deleting: return 4
      case .unknown: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .failed: return "FAILED"
      case .deploying: return "DEPLOYING"
      case .deleting: return "DELETING"
      case .unknown: return "UNKNOWN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "FAILED": self = .failed
      case "DEPLOYING": self = .deploying
      case "DELETING": self = .deleting
      case "UNKNOWN": self = .unknown
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .failed
      case 3: self = .deploying
      case 4: self = .deleting
      case 5: self = .unknown
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .active: return try container.encode("ACTIVE")
      case .failed: return try container.encode("FAILED")
      case .deploying: return try container.encode("DEPLOYING")
      case .deleting: return try container.encode("DELETING")
      case .unknown: return try container.encode("UNKNOWN")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.functions.v2.Function"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
