// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIamV1
import GoogleLongrunning
import GoogleRpc
import Logging

/// Google Cloud Functions is used to deploy functions that are executed by
/// Google in response to various events. Data connected with that event is
/// passed to a function as the input data.
///
/// A **function** is a resource which describes a function that should be
/// executed and how it is triggered.
///
/// @Snippet(path: "FunctionServiceQuickstart")
public protocol FunctionService {
  /// Returns a function with the given name from the requested project.
  ///
  /// @Snippet(path: "FunctionService_GetFunction")
  func getFunction(request: GetFunctionRequest) async throws -> GoogleCloudFunctionsV2.Function

  /// Returns a list of functions that belong to the requested project.
  ///
  /// @Snippet(path: "FunctionService_ListFunctions")
  func listFunctions(request: ListFunctionsRequest) async throws
    -> GoogleCloudFunctionsV2.ListFunctionsResponse

  /// Returns a list of functions that belong to the requested project.
  func listFunctions(
    byItem: ListFunctionsRequest
  ) throws -> any AsyncSequence<Function, Swift.Error>

  /// Creates a new function. If a function with the given name already exists in
  /// the specified project, the long running operation will return
  /// `ALREADY_EXISTS` error.
  ///
  /// @Snippet(path: "FunctionService_CreateFunction")
  func createFunction(request: CreateFunctionRequest) async throws -> GoogleLongrunning.Operation

  /// Creates a new function. If a function with the given name already exists in
  /// the specified project, the long running operation will return
  /// `ALREADY_EXISTS` error.
  func createFunction(withPolling: CreateFunctionRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Function>

  /// Updates existing function.
  ///
  /// @Snippet(path: "FunctionService_UpdateFunction")
  func updateFunction(request: UpdateFunctionRequest) async throws -> GoogleLongrunning.Operation

  /// Updates existing function.
  func updateFunction(withPolling: UpdateFunctionRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Function>

  /// Deletes a function with the given name from the specified project. If the
  /// given function is used by some trigger, the trigger will be updated to
  /// remove this function.
  ///
  /// @Snippet(path: "FunctionService_DeleteFunction")
  func deleteFunction(request: DeleteFunctionRequest) async throws -> GoogleLongrunning.Operation

  /// Deletes a function with the given name from the specified project. If the
  /// given function is used by some trigger, the trigger will be updated to
  /// remove this function.
  func deleteFunction(withPolling: DeleteFunctionRequest) async throws -> any GoogleCloudGax
    .PollableOperation<GoogleCloudWkt.Empty>

  /// Returns a signed URL for uploading a function source code.
  /// For more information about the signed URL usage see:
  /// https://cloud.google.com/storage/docs/access-control/signed-urls.
  /// Once the function source code upload is complete, the used signed
  /// URL should be provided in CreateFunction or UpdateFunction request
  /// as a reference to the function source code.
  ///
  /// When uploading source code to the generated signed URL, please follow
  /// these restrictions:
  ///
  /// * Source file type should be a zip file.
  /// * No credentials should be attached - the signed URLs provide access to the
  ///   target bucket using internal service identity; if credentials were
  ///   attached, the identity from the credentials would be used, but that
  ///   identity does not have permissions to upload files to the URL.
  ///
  /// When making a HTTP PUT request, specify this header:
  ///
  /// * `content-type: application/zip`
  ///
  /// Do not specify this header:
  ///
  /// * `Authorization: Bearer YOUR_TOKEN`
  ///
  /// @Snippet(path: "FunctionService_GenerateUploadUrl")
  func generateUploadUrl(request: GenerateUploadUrlRequest) async throws
    -> GoogleCloudFunctionsV2.GenerateUploadUrlResponse

  /// Returns a signed URL for downloading deployed function source code.
  /// The URL is only valid for a limited period and should be used within
  /// 30 minutes of generation.
  /// For more information about the signed URL usage see:
  /// https://cloud.google.com/storage/docs/access-control/signed-urls
  ///
  /// @Snippet(path: "FunctionService_GenerateDownloadUrl")
  func generateDownloadUrl(request: GenerateDownloadUrlRequest) async throws
    -> GoogleCloudFunctionsV2.GenerateDownloadUrlResponse

  /// Returns a list of runtimes that are supported for the requested project.
  ///
  /// @Snippet(path: "FunctionService_ListRuntimes")
  func listRuntimes(request: ListRuntimesRequest) async throws
    -> GoogleCloudFunctionsV2.ListRuntimesResponse

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "FunctionService_ListLocations")
  func listLocations(request: ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse

  /// Lists information about the supported locations for this service.
  func listLocations(
    byItem: ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "FunctionService_SetIamPolicy")
  func setIamPolicy(request: SetIamPolicyRequest) async throws -> GoogleIamV1.Policy

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "FunctionService_GetIamPolicy")
  func getIamPolicy(request: GetIamPolicyRequest) async throws -> GoogleIamV1.Policy

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "FunctionService_TestIamPermissions")
  func testIamPermissions(request: TestIamPermissionsRequest) async throws
    -> GoogleIamV1.TestIamPermissionsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "FunctionService_ListOperations")
  func listOperations(request: ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func listOperations(
    byItem: ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "FunctionService_GetOperation")
  func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation

  /// Returns a function with the given name from the requested project.
  ///
  /// @Snippet(path: "FunctionService_GetFunction")
  func getFunction(
    request: GetFunctionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFunctionsV2.Function

  /// Returns a list of functions that belong to the requested project.
  ///
  /// @Snippet(path: "FunctionService_ListFunctions")
  func listFunctions(
    request: ListFunctionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFunctionsV2.ListFunctionsResponse

  /// Returns a list of functions that belong to the requested project.
  func listFunctions(
    byItem: ListFunctionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Function, Swift.Error>

  /// Creates a new function. If a function with the given name already exists in
  /// the specified project, the long running operation will return
  /// `ALREADY_EXISTS` error.
  ///
  /// @Snippet(path: "FunctionService_CreateFunction")
  func createFunction(
    request: CreateFunctionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Creates a new function. If a function with the given name already exists in
  /// the specified project, the long running operation will return
  /// `ALREADY_EXISTS` error.
  func createFunction(
    withPolling: CreateFunctionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Function>

  /// Updates existing function.
  ///
  /// @Snippet(path: "FunctionService_UpdateFunction")
  func updateFunction(
    request: UpdateFunctionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Updates existing function.
  func updateFunction(
    withPolling: UpdateFunctionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Function>

  /// Deletes a function with the given name from the specified project. If the
  /// given function is used by some trigger, the trigger will be updated to
  /// remove this function.
  ///
  /// @Snippet(path: "FunctionService_DeleteFunction")
  func deleteFunction(
    request: DeleteFunctionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Deletes a function with the given name from the specified project. If the
  /// given function is used by some trigger, the trigger will be updated to
  /// remove this function.
  func deleteFunction(
    withPolling: DeleteFunctionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<GoogleCloudWkt.Empty>

  /// Returns a signed URL for uploading a function source code.
  /// For more information about the signed URL usage see:
  /// https://cloud.google.com/storage/docs/access-control/signed-urls.
  /// Once the function source code upload is complete, the used signed
  /// URL should be provided in CreateFunction or UpdateFunction request
  /// as a reference to the function source code.
  ///
  /// When uploading source code to the generated signed URL, please follow
  /// these restrictions:
  ///
  /// * Source file type should be a zip file.
  /// * No credentials should be attached - the signed URLs provide access to the
  ///   target bucket using internal service identity; if credentials were
  ///   attached, the identity from the credentials would be used, but that
  ///   identity does not have permissions to upload files to the URL.
  ///
  /// When making a HTTP PUT request, specify this header:
  ///
  /// * `content-type: application/zip`
  ///
  /// Do not specify this header:
  ///
  /// * `Authorization: Bearer YOUR_TOKEN`
  ///
  /// @Snippet(path: "FunctionService_GenerateUploadUrl")
  func generateUploadUrl(
    request: GenerateUploadUrlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFunctionsV2.GenerateUploadUrlResponse

  /// Returns a signed URL for downloading deployed function source code.
  /// The URL is only valid for a limited period and should be used within
  /// 30 minutes of generation.
  /// For more information about the signed URL usage see:
  /// https://cloud.google.com/storage/docs/access-control/signed-urls
  ///
  /// @Snippet(path: "FunctionService_GenerateDownloadUrl")
  func generateDownloadUrl(
    request: GenerateDownloadUrlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFunctionsV2.GenerateDownloadUrlResponse

  /// Returns a list of runtimes that are supported for the requested project.
  ///
  /// @Snippet(path: "FunctionService_ListRuntimes")
  func listRuntimes(
    request: ListRuntimesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFunctionsV2.ListRuntimesResponse

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "FunctionService_ListLocations")
  func listLocations(
    request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse

  /// Lists information about the supported locations for this service.
  func listLocations(
    byItem: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "FunctionService_SetIamPolicy")
  func setIamPolicy(
    request: SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1.Policy

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "FunctionService_GetIamPolicy")
  func getIamPolicy(
    request: GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1.Policy

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "FunctionService_TestIamPermissions")
  func testIamPermissions(
    request: TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1.TestIamPermissionsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "FunctionService_ListOperations")
  func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "FunctionService_GetOperation")
  func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation
}

extension Clients {
  /// The recommended implementation for ``FunctionService``.
  public class FunctionServiceClient: FunctionService {
    let inner: any FunctionServiceStub

    /// Creates a new `FunctionServiceClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any FunctionServiceStub = try FunctionServiceTransport(options)
      inner = FunctionServiceRetry(inner, options: options)
      if let logger = options.logger {
        inner = FunctionServiceLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// See `FunctionService.getFunction`
    public func getFunction(
      request: GetFunctionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFunctionsV2.Function {
      try await self.inner.getFunction(request: request, options: options)
    }

    /// See `FunctionService.listFunctions`
    public func listFunctions(
      request: ListFunctionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFunctionsV2.ListFunctionsResponse {
      try await self.inner.listFunctions(request: request, options: options)
    }

    /// Returns a list of functions that belong to the requested project.
    public func listFunctions(
      byItem: ListFunctionsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Function, Swift.Error> {
      let listRpc = {
        (token: String) async throws -> GoogleCloudFunctionsV2.ListFunctionsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listFunctions(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `FunctionService.createFunction`
    public func createFunction(
      request: CreateFunctionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.createFunction(request: request, options: options)
    }

    /// Creates a new function. If a function with the given name already exists in
    /// the specified project, the long running operation will return
    /// `ALREADY_EXISTS` error.
    public func createFunction(
      withPolling: CreateFunctionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Function> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<Function>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try Function(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.createFunction(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Function>.State in
        let op = try await self.getOperation(request: .init(name: rawOp.name), options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `FunctionService.updateFunction`
    public func updateFunction(
      request: UpdateFunctionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.updateFunction(request: request, options: options)
    }

    /// Updates existing function.
    public func updateFunction(
      withPolling: UpdateFunctionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Function> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<Function>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try Function(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.updateFunction(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Function>.State in
        let op = try await self.getOperation(request: .init(name: rawOp.name), options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `FunctionService.deleteFunction`
    public func deleteFunction(
      request: DeleteFunctionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.deleteFunction(request: request, options: options)
    }

    /// Deletes a function with the given name from the specified project. If the
    /// given function is used by some trigger, the trigger will be updated to
    /// remove this function.
    public func deleteFunction(
      withPolling: DeleteFunctionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<GoogleCloudWkt.Empty> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<GoogleCloudWkt.Empty>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try GoogleCloudWkt.Empty(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.deleteFunction(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        () async throws -> GoogleCloudGax._PollableOperationImpl<GoogleCloudWkt.Empty>.State in
        let op = try await self.getOperation(request: .init(name: rawOp.name), options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `FunctionService.generateUploadUrl`
    public func generateUploadUrl(
      request: GenerateUploadUrlRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFunctionsV2.GenerateUploadUrlResponse {
      try await self.inner.generateUploadUrl(request: request, options: options)
    }

    /// See `FunctionService.generateDownloadUrl`
    public func generateDownloadUrl(
      request: GenerateDownloadUrlRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFunctionsV2.GenerateDownloadUrlResponse {
      try await self.inner.generateDownloadUrl(request: request, options: options)
    }

    /// See `FunctionService.listRuntimes`
    public func listRuntimes(
      request: ListRuntimesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFunctionsV2.ListRuntimesResponse {
      try await self.inner.listRuntimes(request: request, options: options)
    }

    /// See `FunctionService.listLocations`
    public func listLocations(
      request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self.inner.listLocations(request: request, options: options)
    }

    /// Lists information about the supported locations for this service.
    public func listLocations(
      byItem: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
      let listRpc = { (token: String) async throws -> GoogleCloudLocation.ListLocationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listLocations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `FunctionService.setIamPolicy`
    public func setIamPolicy(
      request: SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIamV1.Policy {
      try await self.inner.setIamPolicy(request: request, options: options)
    }

    /// See `FunctionService.getIamPolicy`
    public func getIamPolicy(
      request: GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIamV1.Policy {
      try await self.inner.getIamPolicy(request: request, options: options)
    }

    /// See `FunctionService.testIamPermissions`
    public func testIamPermissions(
      request: TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIamV1.TestIamPermissionsResponse {
      try await self.inner.testIamPermissions(request: request, options: options)
    }

    /// See `FunctionService.listOperations`
    public func listOperations(
      request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
    public func listOperations(
      byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
      let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `FunctionService.getOperation`
    public func getOperation(
      request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }
  }
}

// Default implementations
extension FunctionService {
  public func getFunction(request: GetFunctionRequest) async throws
    -> GoogleCloudFunctionsV2.Function
  {
    try await self.getFunction(request: request, options: .init())
  }

  public func getFunction(
    request: GetFunctionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFunctionsV2.Function {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listFunctions(request: ListFunctionsRequest) async throws
    -> GoogleCloudFunctionsV2.ListFunctionsResponse
  {
    try await self.listFunctions(request: request, options: .init())
  }

  public func listFunctions(
    request: ListFunctionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFunctionsV2.ListFunctionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listFunctions(
    byItem: ListFunctionsRequest
  ) throws -> any AsyncSequence<Function, Swift.Error> {
    try self.listFunctions(byItem: byItem, options: .init())
  }

  public func listFunctions(
    byItem: ListFunctionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Function, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleCloudFunctionsV2.ListFunctionsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func createFunction(request: CreateFunctionRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.createFunction(request: request, options: .init())
  }

  public func createFunction(
    request: CreateFunctionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createFunction(withPolling: CreateFunctionRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Function>
  {
    try await self.createFunction(withPolling: withPolling, options: .init())
  }

  public func createFunction(
    withPolling: CreateFunctionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Function> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Function>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateFunction(request: UpdateFunctionRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.updateFunction(request: request, options: .init())
  }

  public func updateFunction(
    request: UpdateFunctionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateFunction(withPolling: UpdateFunctionRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Function>
  {
    try await self.updateFunction(withPolling: withPolling, options: .init())
  }

  public func updateFunction(
    withPolling: UpdateFunctionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Function> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Function>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteFunction(request: DeleteFunctionRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.deleteFunction(request: request, options: .init())
  }

  public func deleteFunction(
    request: DeleteFunctionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteFunction(withPolling: DeleteFunctionRequest) async throws -> any GoogleCloudGax
    .PollableOperation<GoogleCloudWkt.Empty>
  {
    try await self.deleteFunction(withPolling: withPolling, options: .init())
  }

  public func deleteFunction(
    withPolling: DeleteFunctionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<GoogleCloudWkt.Empty> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<GoogleCloudWkt.Empty>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func generateUploadUrl(request: GenerateUploadUrlRequest) async throws
    -> GoogleCloudFunctionsV2.GenerateUploadUrlResponse
  {
    try await self.generateUploadUrl(request: request, options: .init())
  }

  public func generateUploadUrl(
    request: GenerateUploadUrlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFunctionsV2.GenerateUploadUrlResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func generateDownloadUrl(request: GenerateDownloadUrlRequest) async throws
    -> GoogleCloudFunctionsV2.GenerateDownloadUrlResponse
  {
    try await self.generateDownloadUrl(request: request, options: .init())
  }

  public func generateDownloadUrl(
    request: GenerateDownloadUrlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFunctionsV2.GenerateDownloadUrlResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listRuntimes(request: ListRuntimesRequest) async throws
    -> GoogleCloudFunctionsV2.ListRuntimesResponse
  {
    try await self.listRuntimes(request: request, options: .init())
  }

  public func listRuntimes(
    request: ListRuntimesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFunctionsV2.ListRuntimesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(request: ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func setIamPolicy(request: SetIamPolicyRequest) async throws -> GoogleIamV1.Policy {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GetIamPolicyRequest) async throws -> GoogleIamV1.Policy {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: TestIamPermissionsRequest) async throws
    -> GoogleIamV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1.TestIamPermissionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
