// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol FunctionServiceStub: Sendable {
    func getFunction(
      request: GetFunctionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFunctionsV2.Function

    func listFunctions(
      request: ListFunctionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFunctionsV2.ListFunctionsResponse

    func createFunction(
      request: CreateFunctionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateFunction(
      request: UpdateFunctionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteFunction(
      request: DeleteFunctionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func generateUploadUrl(
      request: GenerateUploadUrlRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFunctionsV2.GenerateUploadUrlResponse

    func generateDownloadUrl(
      request: GenerateDownloadUrlRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFunctionsV2.GenerateDownloadUrlResponse

    func listRuntimes(
      request: ListRuntimesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFunctionsV2.ListRuntimesResponse

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation
  }
}
