// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Response of `GenerateSourceUploadUrl` method.
public struct GenerateUploadUrlResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The generated Google Cloud Storage signed URL that should be used for a
  /// function source code upload. The uploaded file should be a zip archive
  /// which contains a function.
  public var uploadUrl: Swift.String

  /// The location of the source code in the upload bucket.
  ///
  /// Once the archive is uploaded using the `upload_url` use this field to
  /// set the `function.build_config.source.storage_source`
  /// during CreateFunction and UpdateFunction.
  ///
  /// Generation defaults to 0, as Cloud Storage provides a new generation only
  /// upon uploading a new object or version of an object.
  public var storageSource: StorageSource?

  /// Initialize a new instance of `GenerateUploadUrlResponse`.
  public init(
    uploadUrl: Swift.String = Swift.String(),
    storageSource: StorageSource? = nil,
  ) {
    self.uploadUrl = uploadUrl
    self.storageSource = storageSource
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.functions.v2.GenerateUploadUrlResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
