// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for the `GetFunction` method.
public struct GetFunctionRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the function which details should be obtained.
  public var name: Swift.String

  /// Optional. The optional version of the 1st gen function whose details should
  /// be obtained. The version of a 1st gen function is an integer that starts
  /// from 1 and gets incremented on redeployments. GCF may keep historical
  /// configs for old versions of 1st gen function. This field can be specified
  /// to fetch the historical configs. This field is valid only for GCF 1st gen
  /// function.
  public var revision: Swift.String

  /// Initialize a new instance of `GetFunctionRequest`.
  public init(
    name: Swift.String = Swift.String(),
    revision: Swift.String = Swift.String(),
  ) {
    self.name = name
    self.revision = revision
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.functions.v2.GetFunctionRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
