// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleType

/// Response for the `ListRuntimes` method.
public struct ListRuntimesResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The runtimes that match the request.
  public var runtimes: [ListRuntimesResponse.Runtime] = []

  /// Initialize a new instance of `ListRuntimesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListRuntimesResponse().with { $0.runtimes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Describes a runtime and any special information (e.g., deprecation status)
  /// related to it.
  public struct Runtime: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The name of the runtime, e.g., 'go113', 'nodejs12', etc.
    public var name: Swift.String = Swift.String()

    /// The user facing name, eg 'Go 1.13', 'Node.js 12', etc.
    public var displayName: Swift.String = Swift.String()

    /// The stage of life this runtime is in, e.g., BETA, GA, etc.
    public var stage: ListRuntimesResponse.RuntimeStage = ListRuntimesResponse.RuntimeStage()

    /// Warning messages, e.g., a deprecation warning.
    public var warnings: [Swift.String] = []

    /// The environment for the runtime.
    public var environment: Environment = Environment()

    /// Deprecation date for the runtime.
    public var deprecationDate: GoogleType.Date? = nil

    /// Decommission date for the runtime.
    public var decommissionDate: GoogleType.Date? = nil

    /// Initialize a new instance of `Runtime`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Runtime().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.functions.v2.ListRuntimesResponse.Runtime"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The various stages that a runtime can be in.
  public enum RuntimeStage: Codable, Equatable, Sendable {
    /// Not specified.
    case unspecified
    /// The runtime is in development.
    case development
    /// The runtime is in the Alpha stage.
    case alpha
    /// The runtime is in the Beta stage.
    case beta
    /// The runtime is generally available.
    case ga
    /// The runtime is deprecated.
    case deprecated
    /// The runtime is no longer supported.
    case decommissioned
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .development: return 1
      case .alpha: return 2
      case .beta: return 3
      case .ga: return 4
      case .deprecated: return 5
      case .decommissioned: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RUNTIME_STAGE_UNSPECIFIED"
      case .development: return "DEVELOPMENT"
      case .alpha: return "ALPHA"
      case .beta: return "BETA"
      case .ga: return "GA"
      case .deprecated: return "DEPRECATED"
      case .decommissioned: return "DECOMMISSIONED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RuntimeStage/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RUNTIME_STAGE_UNSPECIFIED": self = .unspecified
      case "DEVELOPMENT": self = .development
      case "ALPHA": self = .alpha
      case "BETA": self = .beta
      case "GA": self = .ga
      case "DEPRECATED": self = .deprecated
      case "DECOMMISSIONED": self = .decommissioned
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RuntimeStage/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .development
      case 2: self = .alpha
      case 3: self = .beta
      case 4: self = .ga
      case 5: self = .deprecated
      case 6: self = .decommissioned
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .development: return try container.encode(1)
      case .alpha: return try container.encode(2)
      case .beta: return try container.encode(3)
      case .ga: return try container.encode(4)
      case .deprecated: return try container.encode(5)
      case .decommissioned: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.functions.v2.ListRuntimesResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
