// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for the `ListFunctions` method.
public struct ListFunctionsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The project and location from which the function should be
  /// listed, specified in the format `projects/*/locations/*` If you want to
  /// list functions in all locations, use "-" in place of a location. When
  /// listing functions in all locations, if one or more location(s) are
  /// unreachable, the response will contain functions from all reachable
  /// locations along with the names of any unreachable locations.
  public var parent: Swift.String = Swift.String()

  /// Maximum number of functions to return per call. The largest allowed
  /// page_size is 1,000, if the page_size is omitted or specified as greater
  /// than 1,000 then it will be replaced as 1,000. The size of the list
  /// response can be less than specified when used with filters.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The value returned by the last
  /// `ListFunctionsResponse`; indicates that
  /// this is a continuation of a prior `ListFunctions` call, and that the
  /// system should return the next page of data.
  public var pageToken: Swift.String = Swift.String()

  /// The filter for Functions that match the filter expression,
  /// following the syntax outlined in https://google.aip.dev/160.
  public var filter: Swift.String = Swift.String()

  /// The sorting order of the resources returned. Value should be a comma
  /// separated list of fields. The default sorting order is ascending.
  /// See https://google.aip.dev/132#ordering.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListFunctionsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListFunctionsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.functions.v2.ListFunctionsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
