// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for the `ListRuntimes` method.
public struct ListRuntimesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The project and location from which the runtimes should be
  /// listed, specified in the format `projects/*/locations/*`
  public var parent: Swift.String

  /// The filter for Runtimes that match the filter expression,
  /// following the syntax outlined in https://google.aip.dev/160.
  public var filter: Swift.String

  /// Initialize a new instance of `ListRuntimesRequest`.
  public init(
    parent: Swift.String = Swift.String(),
    filter: Swift.String = Swift.String(),
  ) {
    self.parent = parent
    self.filter = filter
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.functions.v2.ListRuntimesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
