// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Security patches are only applied when a function is redeployed.
public struct OnDeployUpdatePolicy: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. contains the runtime version which was used during latest
  /// function deployment.
  public var runtimeVersion: Swift.String

  /// Initialize a new instance of `OnDeployUpdatePolicy`.
  public init(
    runtimeVersion: Swift.String = Swift.String(),
  ) {
    self.runtimeVersion = runtimeVersion
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.functions.v2.OnDeployUpdatePolicy"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
