// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The type of the long running operation.
public enum OperationType: Codable, Equatable, Sendable {
  /// Unspecified
  case operationtypeUnspecified
  /// CreateFunction
  case createFunction
  /// UpdateFunction
  case updateFunction
  /// DeleteFunction
  case deleteFunction
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .operationtypeUnspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .operationtypeUnspecified: return 0
    case .createFunction: return 1
    case .updateFunction: return 2
    case .deleteFunction: return 3
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .operationtypeUnspecified: return "OPERATIONTYPE_UNSPECIFIED"
    case .createFunction: return "CREATE_FUNCTION"
    case .updateFunction: return "UPDATE_FUNCTION"
    case .deleteFunction: return "DELETE_FUNCTION"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "OPERATIONTYPE_UNSPECIFIED": self = .operationtypeUnspecified
    case "CREATE_FUNCTION": self = .createFunction
    case "UPDATE_FUNCTION": self = .updateFunction
    case "DELETE_FUNCTION": self = .deleteFunction
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .operationtypeUnspecified
    case 1: self = .createFunction
    case 2: self = .updateFunction
    case 3: self = .deleteFunction
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .operationtypeUnspecified: return try container.encode(0)
    case .createFunction: return try container.encode(1)
    case .updateFunction: return try container.encode(2)
    case .deleteFunction: return try container.encode(3)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
