// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Location of the source in a Google Cloud Source Repository.
public struct RepoSource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// ID of the project that owns the Cloud Source Repository. If omitted, the
  /// project ID requesting the build is assumed.
  public var projectId: Swift.String

  /// Name of the Cloud Source Repository.
  public var repoName: Swift.String

  /// Directory, relative to the source root, in which to run the build.
  ///
  /// This must be a relative path. If a step's `dir` is specified and is an
  /// absolute path, this value is ignored for that step's execution.
  /// eg. helloworld (no leading slash allowed)
  public var dir: Swift.String

  /// Only trigger a build if the revision regex does NOT match the revision
  /// regex.
  public var invertRegex: Swift.Bool

  /// A revision within the Cloud Source Repository must be specified in
  /// one of these ways.
  public var revision: OneOf_Revision?

  /// Initialize a new instance of `RepoSource`.
  public init(
    projectId: Swift.String = Swift.String(),
    repoName: Swift.String = Swift.String(),
    dir: Swift.String = Swift.String(),
    invertRegex: Swift.Bool = Swift.Bool(),
    revision: OneOf_Revision? = nil,
  ) {
    self.projectId = projectId
    self.repoName = repoName
    self.dir = dir
    self.invertRegex = invertRegex
    self.revision = revision
  }

  private enum CodingKeys: String, CodingKey {
    case branchName = "branchName"
    case tagName = "tagName"
    case commitSha = "commitSha"
    case projectId = "projectId"
    case repoName = "repoName"
    case dir = "dir"
    case invertRegex = "invertRegex"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.projectId = try container.decode(Swift.String.self, forKey: .projectId)
    self.repoName = try container.decode(Swift.String.self, forKey: .repoName)
    self.dir = try container.decode(Swift.String.self, forKey: .dir)
    self.invertRegex = try container.decode(Swift.Bool.self, forKey: .invertRegex)

    var revision: OneOf_Revision? = nil
    let revisionCheckAndSet = {
      if revision != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'revision'"))
      }
      revision = $0
    }
    if let branchName = try container.decodeIfPresent(Swift.String.self, forKey: .branchName) {
      try revisionCheckAndSet(.branchName(branchName))
    }
    if let tagName = try container.decodeIfPresent(Swift.String.self, forKey: .tagName) {
      try revisionCheckAndSet(.tagName(tagName))
    }
    if let commitSha = try container.decodeIfPresent(Swift.String.self, forKey: .commitSha) {
      try revisionCheckAndSet(.commitSha(commitSha))
    }
    self.revision = revision
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.projectId, forKey: .projectId)
    try container.encode(self.repoName, forKey: .repoName)
    try container.encode(self.dir, forKey: .dir)
    try container.encode(self.invertRegex, forKey: .invertRegex)

    if let choice = self.revision {
      switch choice {
      case .branchName(let value):
        try container.encode(value, forKey: .branchName)
      case .tagName(let value):
        try container.encode(value, forKey: .tagName)
      case .commitSha(let value):
        try container.encode(value, forKey: .commitSha)
      }
    }
  }

  /// A revision within the Cloud Source Repository must be specified in
  /// one of these ways.
  public enum OneOf_Revision: Codable, Equatable, Sendable {
    /// Regex matching branches to build.
    ///
    /// The syntax of the regular expressions accepted is the syntax accepted by
    /// RE2 and described at https://github.com/google/re2/wiki/Syntax
    case branchName(Swift.String)
    /// Regex matching tags to build.
    ///
    /// The syntax of the regular expressions accepted is the syntax accepted by
    /// RE2 and described at https://github.com/google/re2/wiki/Syntax
    case tagName(Swift.String)
    /// Explicit commit SHA to build.
    case commitSha(Swift.String)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.functions.v2.RepoSource"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
