// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Describes the Service being deployed.
/// Currently Supported : Cloud Run (fully managed).
public struct ServiceConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Name of the service associated with a Function.
  /// The format of this field is
  /// `projects/{project}/locations/{region}/services/{service}`
  public var service: Swift.String = Swift.String()

  /// The function execution timeout. Execution is considered failed and
  /// can be terminated if the function is not completed at the end of the
  /// timeout period. Defaults to 60 seconds.
  public var timeoutSeconds: Swift.Int32 = Swift.Int32()

  /// The amount of memory available for a function.
  /// Defaults to 256M. Supported units are k, M, G, Mi, Gi. If no unit is
  /// supplied the value is interpreted as bytes.
  /// See
  /// https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go
  /// a full description.
  public var availableMemory: Swift.String = Swift.String()

  /// The number of CPUs used in a single container instance.
  /// Default value is calculated from available memory.
  /// Supports the same values as Cloud Run, see
  /// https://cloud.google.com/run/docs/reference/rest/v1/Container#resourcerequirements
  /// Example: "1" indicates 1 vCPU
  public var availableCpu: Swift.String = Swift.String()

  /// Environment variables that shall be available during function execution.
  public var environmentVariables: [Swift.String: Swift.String] = [:]

  /// The limit on the maximum number of function instances that may coexist at a
  /// given time.
  ///
  /// In some cases, such as rapid traffic surges, Cloud Functions may, for a
  /// short period of time, create more instances than the specified max
  /// instances limit. If your function cannot tolerate this temporary behavior,
  /// you may want to factor in a safety margin and set a lower max instances
  /// value than your function can tolerate.
  ///
  /// See the [Max
  /// Instances](https://cloud.google.com/functions/docs/max-instances) Guide for
  /// more details.
  public var maxInstanceCount: Swift.Int32 = Swift.Int32()

  /// The limit on the minimum number of function instances that may coexist at a
  /// given time.
  ///
  /// Function instances are kept in idle state for a short period after they
  /// finished executing the request to reduce cold start time for subsequent
  /// requests. Setting a minimum instance count will ensure that the given
  /// number of instances are kept running in idle state always. This can help
  /// with cold start times when jump in incoming request count occurs after the
  /// idle instance would have been stopped in the default case.
  public var minInstanceCount: Swift.Int32 = Swift.Int32()

  /// The Serverless VPC Access connector that this cloud function can connect
  /// to. The format of this field is `projects/*/locations/*/connectors/*`.
  public var vpcConnector: Swift.String = Swift.String()

  /// The egress settings for the connector, controlling what traffic is diverted
  /// through it.
  public var vpcConnectorEgressSettings: ServiceConfig.VpcConnectorEgressSettings =
    ServiceConfig.VpcConnectorEgressSettings()

  /// The ingress settings for the function, controlling what traffic can reach
  /// it.
  public var ingressSettings: ServiceConfig.IngressSettings = ServiceConfig.IngressSettings()

  /// Output only. URI of the Service deployed.
  public var uri: Swift.String = Swift.String()

  /// The email of the service's service account. If empty, defaults to
  /// `{project_number}-compute@developer.gserviceaccount.com`.
  public var serviceAccountEmail: Swift.String = Swift.String()

  /// Whether 100% of traffic is routed to the latest revision.
  /// On CreateFunction and UpdateFunction, when set to true, the revision being
  /// deployed will serve 100% of traffic, ignoring any traffic split settings,
  /// if any. On GetFunction, true will be returned if the latest revision is
  /// serving 100% of traffic.
  public var allTrafficOnLatestRevision: Swift.Bool = Swift.Bool()

  /// Secret environment variables configuration.
  public var secretEnvironmentVariables: [SecretEnvVar] = []

  /// Secret volumes configuration.
  public var secretVolumes: [SecretVolume] = []

  /// Output only. The name of service revision.
  public var revision: Swift.String = Swift.String()

  /// Sets the maximum number of concurrent requests that each instance
  /// can receive. Defaults to 1.
  public var maxInstanceRequestConcurrency: Swift.Int32 = Swift.Int32()

  /// Security level configure whether the function only accepts https.
  /// This configuration is only applicable to 1st Gen functions with Http
  /// trigger. By default https is optional for 1st Gen functions; 2nd Gen
  /// functions are https ONLY.
  public var securityLevel: ServiceConfig.SecurityLevel = ServiceConfig.SecurityLevel()

  /// Optional. The binary authorization policy to be checked when deploying the
  /// Cloud Run service.
  public var binaryAuthorizationPolicy: Swift.String = Swift.String()

  /// Initialize a new instance of `ServiceConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ServiceConfig().with { $0.service = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Available egress settings.
  ///
  /// This controls what traffic is diverted through the VPC Access Connector
  /// resource. By default PRIVATE_RANGES_ONLY will be used.
  public enum VpcConnectorEgressSettings: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Use the VPC Access Connector only for private IP space from RFC1918.
    case privateRangesOnly
    /// Force the use of VPC Access Connector for all egress traffic from the
    /// function.
    case allTraffic
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .privateRangesOnly: return 1
      case .allTraffic: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VPC_CONNECTOR_EGRESS_SETTINGS_UNSPECIFIED"
      case .privateRangesOnly: return "PRIVATE_RANGES_ONLY"
      case .allTraffic: return "ALL_TRAFFIC"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:VpcConnectorEgressSettings/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VPC_CONNECTOR_EGRESS_SETTINGS_UNSPECIFIED": self = .unspecified
      case "PRIVATE_RANGES_ONLY": self = .privateRangesOnly
      case "ALL_TRAFFIC": self = .allTraffic
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:VpcConnectorEgressSettings/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .privateRangesOnly
      case 2: self = .allTraffic
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .privateRangesOnly: return try container.encode(1)
      case .allTraffic: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Available ingress settings.
  ///
  /// This controls what traffic can reach the function.
  ///
  /// If unspecified, ALLOW_ALL will be used.
  public enum IngressSettings: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Allow HTTP traffic from public and private sources.
    case allowAll
    /// Allow HTTP traffic from only private VPC sources.
    case allowInternalOnly
    /// Allow HTTP traffic from private VPC sources and through GCLB.
    case allowInternalAndGclb
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .allowAll: return 1
      case .allowInternalOnly: return 2
      case .allowInternalAndGclb: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "INGRESS_SETTINGS_UNSPECIFIED"
      case .allowAll: return "ALLOW_ALL"
      case .allowInternalOnly: return "ALLOW_INTERNAL_ONLY"
      case .allowInternalAndGclb: return "ALLOW_INTERNAL_AND_GCLB"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:IngressSettings/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "INGRESS_SETTINGS_UNSPECIFIED": self = .unspecified
      case "ALLOW_ALL": self = .allowAll
      case "ALLOW_INTERNAL_ONLY": self = .allowInternalOnly
      case "ALLOW_INTERNAL_AND_GCLB": self = .allowInternalAndGclb
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:IngressSettings/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .allowAll
      case 2: self = .allowInternalOnly
      case 3: self = .allowInternalAndGclb
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .allowAll: return try container.encode(1)
      case .allowInternalOnly: return try container.encode(2)
      case .allowInternalAndGclb: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Available security level settings.
  ///
  /// This enforces security protocol on function URL.
  ///
  /// Security level is only configurable for 1st Gen functions, If unspecified,
  /// SECURE_OPTIONAL will be used. 2nd Gen functions are SECURE_ALWAYS ONLY.
  public enum SecurityLevel: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Requests for a URL that match this handler that do not use HTTPS are
    /// automatically redirected to the HTTPS URL with the same path. Query
    /// parameters are reserved for the redirect.
    case secureAlways
    /// Both HTTP and HTTPS requests with URLs that match the handler succeed
    /// without redirects. The application can examine the request to determine
    /// which protocol was used and respond accordingly.
    case secureOptional
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .secureAlways: return 1
      case .secureOptional: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SECURITY_LEVEL_UNSPECIFIED"
      case .secureAlways: return "SECURE_ALWAYS"
      case .secureOptional: return "SECURE_OPTIONAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SecurityLevel/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SECURITY_LEVEL_UNSPECIFIED": self = .unspecified
      case "SECURE_ALWAYS": self = .secureAlways
      case "SECURE_OPTIONAL": self = .secureOptional
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SecurityLevel/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .secureAlways
      case 2: self = .secureOptional
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .secureAlways: return try container.encode(1)
      case .secureOptional: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.functions.v2.ServiceConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
