// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The location of the function source code.
public struct Source: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Location of the source.
  /// At least one source needs to be provided for the deployment to succeed.
  public var source: OneOf_Source? = nil

  /// Initialize a new instance of `Source`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Source().with { $0.storageSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case storageSource = "storageSource"
    case repoSource = "repoSource"
    case gitUri = "gitUri"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let storageSource = try container.decodeIfPresent(
      StorageSource?.self, forKey: .storageSource)
    {
      try sourceCheckAndSet(.storageSource(storageSource))
    }
    if let repoSource = try container.decodeIfPresent(RepoSource?.self, forKey: .repoSource) {
      try sourceCheckAndSet(.repoSource(repoSource))
    }
    if let gitUri = try container.decodeIfPresent(Swift.String.self, forKey: .gitUri) {
      try sourceCheckAndSet(.gitUri(gitUri))
    }
    self.source = source
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.source {
      switch choice {
      case .storageSource(let value):
        try container.encode(value, forKey: .storageSource)
      case .repoSource(let value):
        try container.encode(value, forKey: .repoSource)
      case .gitUri(let value):
        try container.encode(value, forKey: .gitUri)
      }
    }
  }

  /// Location of the source.
  /// At least one source needs to be provided for the deployment to succeed.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// If provided, get the source from this location in Google Cloud Storage.
    indirect case storageSource(StorageSource?)
    /// If provided, get the source from this location in a Cloud Source
    /// Repository.
    indirect case repoSource(RepoSource?)
    /// If provided, get the source from GitHub repository. This option is valid
    /// only for GCF 1st Gen function.
    /// Example: https://github.com/<user>/<repo>/blob/<commit>/<path-to-code>
    case gitUri(Swift.String)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.functions.v2.Source"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
