// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Provenance of the source. Ways to find the original source, or verify that
/// some source was used for this build.
public struct SourceProvenance: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A copy of the build's `source.storage_source`, if exists, with any
  /// generations resolved.
  public var resolvedStorageSource: StorageSource? = nil

  /// A copy of the build's `source.repo_source`, if exists, with any
  /// revisions resolved.
  public var resolvedRepoSource: RepoSource? = nil

  /// A copy of the build's `source.git_uri`, if exists, with any commits
  /// resolved.
  public var gitUri: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SourceProvenance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SourceProvenance().with { $0.resolvedStorageSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let resolvedStorageSource = CodingKeys(stringValue: "resolvedStorageSource")
    static let resolvedRepoSource = CodingKeys(stringValue: "resolvedRepoSource")
    static let gitUri = CodingKeys(stringValue: "gitUri")

    static let _knownKeys: Set<Swift.String> = [
      "resolvedStorageSource",
      "resolvedRepoSource",
      "gitUri",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.resolvedStorageSource = try container.decodeIfPresent(
      StorageSource.self, forKey: .resolvedStorageSource)
    self.resolvedRepoSource = try container.decodeIfPresent(
      RepoSource.self, forKey: .resolvedRepoSource)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gitUri) {
      self.gitUri = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.resolvedStorageSource, forKey: .resolvedStorageSource)
    try container.encodeIfPresent(self.resolvedRepoSource, forKey: .resolvedRepoSource)
    try container.encode(self.gitUri, forKey: .gitUri)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.functions.v2.SourceProvenance"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
