// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Provenance of the source. Ways to find the original source, or verify that
/// some source was used for this build.
public struct SourceProvenance: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A copy of the build's `source.storage_source`, if exists, with any
  /// generations resolved.
  public var resolvedStorageSource: StorageSource?

  /// A copy of the build's `source.repo_source`, if exists, with any
  /// revisions resolved.
  public var resolvedRepoSource: RepoSource?

  /// A copy of the build's `source.git_uri`, if exists, with any commits
  /// resolved.
  public var gitUri: Swift.String

  /// Initialize a new instance of `SourceProvenance`.
  public init(
    resolvedStorageSource: StorageSource? = nil,
    resolvedRepoSource: RepoSource? = nil,
    gitUri: Swift.String = Swift.String(),
  ) {
    self.resolvedStorageSource = resolvedStorageSource
    self.resolvedRepoSource = resolvedRepoSource
    self.gitUri = gitUri
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.functions.v2.SourceProvenance"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
