// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Each Stage of the deployment process
public struct Stage: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name of the Stage. This will be unique for each Stage.
  public var name: Stage.Name = Stage.Name()

  /// Message describing the Stage
  public var message: Swift.String = Swift.String()

  /// Current state of the Stage
  public var state: Stage.State = Stage.State()

  /// Resource of the Stage
  public var resource: Swift.String = Swift.String()

  /// Link to the current Stage resource
  public var resourceUri: Swift.String = Swift.String()

  /// State messages from the current Stage.
  public var stateMessages: [StateMessage] = []

  /// Initialize a new instance of `Stage`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Stage().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Possible names for a Stage
  public enum Name: Codable, Equatable, Sendable {
    case unspecified
    case artifactRegistry
    case build
    case service
    case trigger
    case serviceRollback
    case triggerRollback
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .artifactRegistry: return 1
      case .build: return 2
      case .service: return 3
      case .trigger: return 4
      case .serviceRollback: return 5
      case .triggerRollback: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "NAME_UNSPECIFIED"
      case .artifactRegistry: return "ARTIFACT_REGISTRY"
      case .build: return "BUILD"
      case .service: return "SERVICE"
      case .trigger: return "TRIGGER"
      case .serviceRollback: return "SERVICE_ROLLBACK"
      case .triggerRollback: return "TRIGGER_ROLLBACK"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "NAME_UNSPECIFIED": self = .unspecified
      case "ARTIFACT_REGISTRY": self = .artifactRegistry
      case "BUILD": self = .build
      case "SERVICE": self = .service
      case "TRIGGER": self = .trigger
      case "SERVICE_ROLLBACK": self = .serviceRollback
      case "TRIGGER_ROLLBACK": self = .triggerRollback
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .artifactRegistry
      case 2: self = .build
      case 3: self = .service
      case 4: self = .trigger
      case 5: self = .serviceRollback
      case 6: self = .triggerRollback
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .artifactRegistry: return try container.encode(1)
      case .build: return try container.encode(2)
      case .service: return try container.encode(3)
      case .trigger: return try container.encode(4)
      case .serviceRollback: return try container.encode(5)
      case .triggerRollback: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible states for a Stage
  public enum State: Codable, Equatable, Sendable {
    case unspecified
    case notStarted
    case inProgress
    case complete
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .notStarted: return 1
      case .inProgress: return 2
      case .complete: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .notStarted: return "NOT_STARTED"
      case .inProgress: return "IN_PROGRESS"
      case .complete: return "COMPLETE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "NOT_STARTED": self = .notStarted
      case "IN_PROGRESS": self = .inProgress
      case "COMPLETE": self = .complete
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .notStarted
      case 2: self = .inProgress
      case 3: self = .complete
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .notStarted: return try container.encode(1)
      case .inProgress: return try container.encode(2)
      case .complete: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.functions.v2.Stage"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
